meetbot/main.go
- I basically just put the kbfs file reading stuff into another function, for parity with the githubbot
=> Refactor kbfs read to getOAuthConfig function

base/base.go, githubbot/githubbot/handler.go, meetbot/meetbot/handler.go, pollbot/pollbot/handler.go, pollbot/pollbot/http.go, triviabot/triviabot/handler.go, webhookbot/webhookbot/handler.go
Default to `ChatDebug` instead of just `Debug`
=> Refactor Errors

githubbot/githubbot/db.go, githubbot/githubbot/db.sql, githubbot/githubbot/handler.go, githubbot/githubbot/http.go, githubbot/githubbot/util.go, githubbot/main.go
Adds a `!github mentions <stop/enable>` command to allow people to never get mentioned by githubbot
=> feat: put user lookup behind a flag

go.mod, go.sum
=> bump api lib

go.mod, go.sum, triviabot/triviabot/session.go
depends on https://github.com/keybase/go-keybase-chat-bot/pull/47
- if you're in a small conv < 4 and answer incorrectly you're stuck waiting until the timeout so now the bot moves on
- bot also says what the correct answer was if the question is skipped
=> trivia bot usability

base/base.go, base/output.go, base/util.go, githubbot/githubbot/db.go, githubbot/githubbot/handler.go, githubbot/githubbot/http.go, githubbot/githubbot/util.go, go.mod, go.sum, pollbot/pollbot/db.go, pollbot/pollbot/handler.go, pollbot/pollbot/vote.go, triviabot/triviabot/db.go, triviabot/triviabot/handler.go, triviabot/triviabot/session.go, webhookbot/webhookbot/db.go, webhookbot/webhookbot/handler.go
depends on https://github.com/keybase/client/pull/21975 and https://github.com/keybase/go-keybase-chat-bot/pull/45
=> Use APIConvID type

githubbot/githubbot/handler.go, githubbot/githubbot/util.go, githubbot/main.go
- Move `!github watch <namespace/repo> <branch>` to `!github subscribe <namespace/repo> <branch>`
=> Move watch command to subscribe

gcalbot/main.go, meetbot/main.go, pollbot/main.go, triviabot/main.go, webhookbot/main.go
As mentioned here: https://github.com/keybase/managed-bots/pull/61/files#r368015108
=> Add return 3

gitlabbot/README.md, gitlabbot/main.go
- Removed `read_user` scope (subset of `api`)
- Added docs about scopes and Callback URLs
=> Add scope and doc updates

jirabot/package.json, jirabot/src/bot.ts, jirabot/src/cmd-auth.ts, jirabot/src/cmd-comment.ts, jirabot/src/cmd-config.ts, jirabot/src/cmd-new.ts, jirabot/src/errors.ts, jirabot/src/message.ts, jirabot/src/utils.ts
CI will fail because 3.3.0 is not published yet, but this should work with https://github.com/keybase/keybase-bot/pull/204
=> jirabot: fix restricted bot

base/base.go, gcalbot/db.sql, gcalbot/gcalbot/account.go, gcalbot/gcalbot/db.go, gcalbot/gcalbot/handler.go, gcalbot/gcalbot/http.go, gcalbot/gcalbot/invite.go, gcalbot/gcalbot/webhook.go, gcalbot/main.go
Adds autorenewing of expiring channels
=> gcalbot invite improvements

jirabot/src/bot-config.ts, jirabot/src/bot.ts, jirabot/src/cmd-auth.ts, jirabot/src/cmd-comment.ts, jirabot/src/cmd-config.ts, jirabot/src/cmd-new.ts, jirabot/src/cmd-search.ts, jirabot/src/configs.ts, jirabot/src/errors.ts, jirabot/src/index.ts, jirabot/src/jira.ts, jirabot/src/message.ts, jirabot/src/utils.ts, jirabot/yarn.lock
* load jira related metadata from jira and deprecate a bunch of jira related fields in bot-configi
* automatically start oauth flow for users who haven't auth'ed
* say hi when added to a channel
* bug fixes and wording tweaks
=> jirabot Orange Box

base/util.go, go.mod, go.sum
depends on https://github.com/keybase/go-keybase-chat-bot/pull/48
=> dont' say hello in convs you created

base/oauth.go, base/util.go, gcalbot/gcalbot/http.go, meetbot/meetbot/http.go
=> oauth html refactor

jirabot/package.json, jirabot/src/bot.ts
CI will fail until 3.3.1 is published.
=> jirabot: don't say hi in bot created conversations

gitlabbot/gitlabbot/handler.go
- DM's instead of into the chat where it was commanded for project set up message.
=> Slide into DMs - GitLab bot

jirabot/src/bot.ts, jirabot/src/cmd-feed.ts, jirabot/src/configs.ts, jirabot/src/constants.ts, jirabot/src/errors.ts, jirabot/src/handle-webhook-event.ts, jirabot/src/http-server.ts, jirabot/src/index.ts, jirabot/src/jira-oauth.ts, jirabot/src/jira.ts, jirabot/src/message.ts, jirabot/src/utils.ts
depends on https://github.com/floralvikings/jira-connector/pull/238 Although the `dist/main.js` here is built with my fork so it's deployable.
=> jirabot: basic feed subscriptions

gcalbot/gcalbot/webhook.go
Fixes a bug causing all past invites to be sent out initially
From https://developers.google.com/calendar/v3/sync#initial_full_sync:
> If the result set is too large and the response gets paginated, then the nextSyncToken field is present only on the very last page.
=> gcalbot: fix incremental sync

gitlabbot/gitlabbot/handler.go
addresses https://github.com/keybase/managed-bots/issues/111
=> Allow subgroups in gitlab

gcalbot/gcalbot/event.go
Only shows the organizer if it is not yourself, and improves multiline descriptions. Also puts the description at the end of the event (always)
=> gcalbot: improve event formatting

gitlabbot/db.sql, gitlabbot/gitlabbot/db.go, gitlabbot/gitlabbot/http.go, gitlabbot/gitlabbot/util.go
- On receiving events that no one is currently subscribed, we notify people subscribed on that repo if they want to subscribe to that branch (once)
=> Fix Default Branch Bug

gitlabbot/gitlabbot/db.go, gitlabbot/gitlabbot/handler.go, gitlabbot/main.go
Example for listing subscriptions
- **owner/repo**
- master
- testbranch
- **owner/repo2**
=> List subscriptions for Gitlab Bot

githubbot/githubbot/db.go, githubbot/githubbot/handler.go, githubbot/githubbot/util.go, githubbot/migrations/defaultBranch.go
Adds a small script to backfill default branch rows after changes from #146
=> Add default branch backfill migration

jirabot/package.json, jirabot/src/bot-config.ts, jirabot/src/bot.ts, jirabot/src/cmd-debug.ts, jirabot/src/message.ts
depends on https://github.com/keybase/keybase-bot/pull/217
=> add `!jira debug` for logSend and pprof

gcalbot/gcalbot/webhook.go
Fixes an issue where the "nextSyncToken" was not set during a subscription. This meant that users might get invites for future events that they had already been invited to before subscribing to the bot.
=> gcalbot: initial subscription token fix

gcalbot/gcalbot/html.go, gcalbot/gcalbot/http.go, gcalbot/gcalbot/util.go
=> gcalbot: new web config design

gcalbot/gcalbot/handler.go, meetbot/meetbot/handler.go
=> fix new conv typo

go.mod, go.sum
=> use updated bot lib [HOTPOT-2027]

canarybot/README.md, gcalbot/README.md, githubbot/README.md, gitlabbot/README.md, meetbot/README.md, pollbot/README.md, triviabot/README.md, webhookbot/README.md
depends on https://github.com/keybase/client/pull/22719
=> clear cmds

gcalbot/gcalbot/handler.go, gcalbot/gcalbot/html.go, gcalbot/gcalbot/http.go, gcalbot/gcalbot/util.go
=> gcalbot web config tweaks

canarybot/README.md, gcalbot/README.md, githubbot/README.md, gitlabbot/README.md, meetbot/README.md, pollbot/README.md, triviabot/README.md, webhookbot/README.md
depends on https://github.com/keybase/client/pull/22721
=> conv info in readmes

go.mod, go.sum
=> update bot lib

gcalbot/gcalbot/reminderscheduler/sync.go
When you have events coming up soon, this change will ensure that reminders are queued for those events right after you subscribe to reminders (ie. if I have an existing event at 4:10 and I subscribe to 5 minute reminders at 4:04, I will receive a reminder at 4:05)
=> gcalbot: queue new reminders on new subscription

gcalbot/gcalbot/oauth.go
When you create a new account using `!gcal accounts connect`, default notifications (invite & 5 minute reminder) will be set for the account's primary calendar upon authentication. The oauth link redirects to the config page for the primary calendar, so this is visible to the user.
=> gcalbot: set default notifications for new account

gcalbot/gcalbot/html.go, gcalbot/gcalbot/http.go
=> gcalbot: select improvements

base/oauth.go, base/util.go, gcalbot/gcalbot/handler.go, gcalbot/gcalbot/http.go, githubbot/githubbot/handler.go, webhookbot/webhookbot/handler.go
cc @marceloneil @hyperobject since this affects github/gcal bots
=> allow team writers to configure bots instead of only admins

gcalbot/gcalbot/event.go
If some events have the same start time, sort them alphabetically.
=> gcalbot: sort daily schedule items

gcalbot/gcalbot/html.go
Restructure the form vertically + support mobile (thanks @hyperobject!)
=> gcalbot ui improvements

base/output.go
Error from the server which is caused by a deleted conversation, so just send it to debug
=> send another deleted conversation error to debug

base/oauth.go
Should test with Google's oauth before merging (ie. meetbot)
=> Renew OAuth tokens and store updated tokens

zoombot/zoombot/api.go, zoombot/zoombot/handler.go
=> zoom: surface rate limit error

githubbot/githubbot/handler.go, meetbot/meetbot/handler.go, zoombot/zoombot/handler.go
=> oauth copy

gitlabbot/gitlabbot/util.go, gitlabbot/gitlabbot/util_test.go
Addresses https://github.com/keybase/managed-bots/issues/120#issuecomment-602416991
=> Drop .git suffix for gitlab urls

base/multi.go, base/server.go, go.mod, go.sum
depends on https://github.com/keybase/go-keybase-chat-bot/pull/64
=>  use new lib version, log heartbeat

base/util.go, go.mod, go.sum, macrobot/db.sql, macrobot/macrobot/db.go, macrobot/macrobot/handler.go, macrobot/main.go
=> per conv ads

go.mod, go.sum, macrobot/macrobot/handler.go
Depends on https://github.com/keybase/go-keybase-chat-bot/pull/71
=> macrobot: clear cmds on remove

jirabot/src/context.ts, jirabot/src/index.ts
Reverts keybase/managed-bots#259
=> Revert "try to send logs when unhanlded promise rejection happens"

macrobot/macrobot/utils.go, macrobot/main.go
=> update copy about updating a macro

.travis.yml, base/git/git.go, base/server.go, githubbot/main.go, githubbot/migrations/default_branch.go, gitlabbot/gitlabbot/http.go, go.mod, go.sum, webhookbot/webhookbot/http.go, zoombot/zoombot/api.go
=> test against the latest versions of go

gcalbot/gcalbot/reminderscheduler/sync.go, gcalbot/gcalbot/schedulescheduler/send.go, webhookbot/webhookbot/http.go
=> downgrade message send fail to debug

base/server.go, gcalbot/gcalbot/webhook.go, go.mod, go.sum
=> Upgrade go-keybase-chatbot lib

triviabot/triviabot/session.go
=> fix trivabot race

README.md, gcalbot/README.md, meetbot/README.md, zoombot/README.md, zoombot/SUPPORT.md, zoombot/main.go, zoombot/zoombot/http.go, zoombot/zoombot/type.go
=> Use secret token instead of verification token for zoombot
