keybase/managed-bots

githubbot/githubbot/util.go
adds checks for other check suite states and makes sure that the message is non-empty before appending an @ mention
=> fix: handle other check suite statuses

githubbot/githubbot/handler.go
Sets mention preferences to `allowMention` instead of always true
=> fix: set user preferences based on what a user wants

githubbot/README.md
This PR adds docs for running the GitHub bot.
=> githubbot readme

githubbot/db.sql, githubbot/githubbot/db.go, githubbot/githubbot/handler.go, githubbot/githubbot/http.go, githubbot/githubbot/util.go, githubbot/main.go
This PR changes a bunch of stuff to make it possible to parse CI events using the Status API and read PR information from private repos:
* parses CheckRun and Status events instead of CheckSuite events
* fetches oauth token for convID before formatting messages in `http.go`
* stores the oauth identifier in the `subscriptions` table to allow convID => token fetching
* bolds GitHub usernames for better readability
* adds `!github auth` command for checking github auth without subscribing
=> Parse all CI events, use OAuth client in webhook handler

base/oauth.go, githubbot/README.md, githubbot/db.sql, githubbot/githubbot/db.go, githubbot/githubbot/handler.go, githubbot/githubbot/http.go, githubbot/githubbot/util.go, githubbot/main.go, go.mod, go.sum
This is a large refactor of how the bot authenticates with the GitHub API and how messages are handled. Overview of the changes:
* The webhook handler now authenticates and gets conversations with the repo and installation ID 
* User-based OAuth is now linked 1-1 from keybase user to github oauth token. These tokens are only used to make sure you're authorized to link a GitHub app installation with a conversation ID.
* Subscriptions are now `(conv_id, repo, installation_id)`. Branches have been moved to a new `branches` table, and are only used to keep track of which push events to send notifications for. 
* There is a new `features` table which keeps track of which events should be parsed for a given `(conv_id, repo)` pair. The un/subscribe commands now can take either an event type or a …
=> Migrate to Github Apps API, add event preferences

githubbot/README.md, githubbot/githubbot/handler.go, githubbot/main.go, gitlabbot/README.md, gitlabbot/main.go
There was a bug where reading the bot secret from its own file would add an extra newline character, causing signature verifications to fail. This PR moves the bot secret into credentials.json alongside other config options. cc @Daniel-Wang
=> feat: read webhook secret from credentials.json

gitlabbot/README.md, gitlabbot/db.sql, gitlabbot/gitlabbot/db.go, gitlabbot/gitlabbot/handler.go, gitlabbot/gitlabbot/http.go, gitlabbot/gitlabbot/util.go, gitlabbot/main.go
GitLab's API scope gives too much control to the bot, so we will scrap the current flow
New Flow:
1. GitLab bot sends the user two things: the webhook url and the validation token
2. The user will then paste these into their project creating a Keybase GitLab webhook
Things removed:
- The entire OAuth flow
- All API calls made from the app
=> Remove OAuth For GitLab bot

githubbot/githubbot/http.go, githubbot/githubbot/util.go
Turns out the `Sender` user in GitHub events basically means nothing for CI events and some others, so this PR changes the author fetching to be a little more specific (and uses some API calls to get information when the webhook isn't detailed enough on its own). Also references the github username that caused a CI event if they don't have mentions enabled, and moves some noisier errors to `Debug` instead of erroring.
=> githubbot: more specific author fetching

githubbot/db.sql, githubbot/githubbot/db.go, githubbot/githubbot/handler.go, githubbot/githubbot/http.go, githubbot/githubbot/util.go, githubbot/main.go
changes the mentions preferences so you can have separate mention preferences per convo (basically just adding `conv_id` as a column in the database and getting stuff based on that)
=> feat: make user prefs per convo

githubbot/githubbot/handler.go, githubbot/main.go, gitlabbot/gitlabbot/handler.go
Adds app installation link in more places, changes `username/repo` to `owner/repo`, and makes help text a little more clear about what happens if you leave off the branch/event type arg.
=> Github bot copy tweaks

gcalbot/db.sql, gcalbot/gcalbot/account.go, gcalbot/gcalbot/calendar.go, gcalbot/gcalbot/db.go, gcalbot/gcalbot/event.go, gcalbot/gcalbot/handler.go, gcalbot/gcalbot/invite.go, gcalbot/gcalbot/reminder.go, gcalbot/gcalbot/reminderscheduler/main.go, gcalbot/gcalbot/reminderscheduler/send.go, gcalbot/gcalbot/reminderscheduler/sync.go, gcalbot/gcalbot/reminderscheduler/type.go, gcalbot/gcalbot/reminderscheduler/util.go, gcalbot/gcalbot/util.go, gcalbot/gcalbot/util_test.go, gcalbot/gcalbot/webhook.go, gcalbot/main.go
Allows you to set reminders for 0-60 minutes before events for an account's primary calendar sent to you over direct message. This PR does not add support for other calendars or channels.
```
!gcal reminders subscribe personal 0
!gcal reminders subscribe family 5
!gcal reminders subscribe work 60
!gcal reminders unsubscribe personal 0
!gcal reminders unsubscribe family 5
!gcal reminders unsubscribe work 60
!gcal reminders list personal
!gcal reminders list work
```
=> gcalbot reminders

githubbot/githubbot/db.go
Some code that was missed during a refactor, the unwatch branch function was trying to delete from `subscriptions` instead of `branches`
=> fix: delete branches from correct table

githubbot/githubbot/http.go
Adds additional checks for an issue where the webhook handler would try to access element 0 of an empty list, causing a panic in the http handler.
=> fix: add check for pull request list length

gitlabbot/gitlabbot/http.go
Since this check can fail whenever you have multiple webhooks on the same repo, this isn't really an issue we need to send a full error for.
=> fix: demote gitlab secret validation errors to debug

webhookbot/webhookbot/http.go
addresses https://github.com/keybase/managed-bots/issues/112
=> parse webhook bodies

gcalbot/gcalbot/handler.go, githubbot/githubbot/handler.go, githubbot/githubbot/http.go, gitlabbot/gitlabbot/handler.go, meetbot/meetbot/handler.go, triviabot/triviabot/handler.go, webhookbot/webhookbot/http.go
uses SetPrefix on handler stats, adds webhook stats (success, invalid payload, disabled feature hooks)
=> add webhook stats to ghbot

githubbot/githubbot/http.go
The Github API returns some pull requests we don't really want to associate with a particular check run/status event (i.e. ones that have the subscribed repo as the head, not the base), which makes for some really confusing messages and errors. This PR fixes that by filtering out PRs in status and check run events that don't have the provided repo as the base.
=> fix: filter pull requests without repo as base in status events

githubbot/githubbot/http.go
Fixes #139 by using the Sender on an issues event instead of the issue's original author.
=> Use IssuesEvent sender for event author

githubbot/githubbot/db.go, githubbot/githubbot/handler.go, githubbot/githubbot/http.go, githubbot/main.go, gitlabbot/gitlabbot/handler.go
Replaces `!github subscribe --list` with `!github list` and adds subscribed branches to the list message
=> Add top-level !github list command

base/oauth.go
If the state is not found or if there is no oauth code provided in the webhook, display an error to the user but don't log it.
We might want to still log this as debug though, and also when no state is found maybe we should prompt the user to run the auth command again rather than continuing to use the same oauth link.
=> OAuth handler log changes

triviabot/triviabot/handler.go
fixes:
```
panic: close of closed channel stack trace: goroutine 37 [running]:
runtime/debug.Stack(0xc000311400, 0xbfecc0, 0xf03b10)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/keybase/managed-bots/base.PanicRecover(0xc00009f8a0)
/managed-bots/base/errors.go:15 +0x57
panic(0xbfecc0, 0xf03b10)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/keybase/managed-bots/triviabot/triviabot.(*session).stop(...)
/managed-bots/triviabot/triviabot/session.go:379
github.com/keybase/managed-bots/triviabot/triviabot.(*Handler).handleStop(0xc000068540, 0xc000528cb4, 0xb, 0x25, 0xc000438300, 0x40, 0xc000528c78, 0x6, 0x0, 0xc000528c80, ...)
/managed-bots/triviabot/triviabot/handler.go:67 +0xe6
github.com/keybase/managed-bots/triviabot/triviabot.(*Handler).HandleCommand(0xc000068540, …
```
=> delete stopped session

gcalbot/gcalbot/event.go, gcalbot/gcalbot/reminderscheduler/send.go, gcalbot/gcalbot/reminderscheduler/sync.go, gcalbot/gcalbot/reminderscheduler/type.go
Before (event with name and event with no name):
After (event with name and event with no name):
=> gcalbot: improve event formatting

gcalbot/gcalbot/http.go
=> gcalbot: daily schedule default time 7:30am -> 10:00am

gcalbot/gcalbot/html.go, gcalbot/gcalbot/http.go
Don't disable the save button if push notifications aren't supported (because the daily schedule can still be set)
=> gcalbot: don't lock the save button on push err

gcalbot/gcalbot/db.go
Fixes a bug where all subscribed calendars would be sent at the same time
=> gcalbot: daily schedule group by time

gitlabbot/gitlabbot/util.go
=> Update hooks URL for GitLab

base/output.go
we weren't catching `oauthHandler: received error response from keybase api: no conversations matched` before
=> Catch no conv error

base/oauth.go, gcalbot/gcalbot/account.go, gcalbot/gcalbot/calendar.go, gcalbot/gcalbot/http.go, gcalbot/gcalbot/invite.go, gcalbot/gcalbot/oauth.go, gcalbot/gcalbot/reminderscheduler/sync.go, gcalbot/gcalbot/schedulescheduler/send.go, gcalbot/gcalbot/webhook.go
Specifically for webhooks and scheduled tasks (ie. reminders, schedules)
=> gcalbot: suppress revoked token errors

macrobot/macrobot/handler.go, macrobot/main.go
This works great, however it doesn't seem like you can clear private ads for a specific team (only clear all ads). If you `!macro remove` when there is only one macro, it will delete the macro and then throw an error. That macro will be stuck in the advertisements for your team/conv. I don't really want to do `clearcommands` because then I would have to rebuild everyones private ads.
=> macrobot: private advertisements

jirabot/package.json, jirabot/src/bot.ts, jirabot/src/cmd-show.ts, jirabot/src/jira.ts, jirabot/src/message.ts, jirabot/src/utils.ts, jirabot/yarn.lock
* add a show cmd
* unfurl ticket if at-mentioned
* don't react with :eyes: in most scenarios
* better error message for invalid `jiraHost` (resolves #222)
=> jirabot: show cmd, unfurl, better error message

jirabot/src/jira.ts
We updated `jiraRespMapper` to add more fields for `!jira show`, but forgot to update the search call to request them. That caused `jiraRespMapper` to throw on response from `!jira search`.
=> fix !jira search

macrobot/macrobot/handler.go
Should update database to remove spaces from macro names.
=> Prevent macro names from having spaces

go.mod, go.sum, macrobot/macrobot/db.go, macrobot/macrobot/handler.go, macrobot/macrobot/utils.go, macrobot/main.go
patch does the following:
- force non team advertisements to be to a specific `conv`
- only advertise `create-for-channel` command to teams
-
=> Fix macrobot advertisements

go.mod, go.sum
Changelist:
https://github.com/keybase/go-keybase-chat-bot/commit/3c61c93bf262e0229fa4c6122214846b5616fdcc
https://github.com/keybase/go-keybase-chat-bot/commit/c60589a4e608014864b71087371025a8b409f521
We can deploy canarybot to make sure that the managed-bots are happy with the gomodule change. It does work locally (macrobot too), but you can never be too careful!
=> Bump go-keybase-chat-bot

githubbot/README.md
Attempts to make the process of setting up a new GitHub app for the bot a little more clear by moving it to its own section
=> move github app config into own section

githubbot/githubbot/handler.go, githubbot/githubbot/http.go, githubbot/githubbot/util.go, githubbot/migrations/default_branch.go, go.mod, go.sum
Bumps go-github from v28 to v31 to remove deprecated GitHub calls and unnecessary API preview headers. Shouldn't be any breaking changes that affect us.
=> bump go-github to v31

jirabot/src/index.ts
I'm realizing the defunct bot usually stops at some warning about "unhandled promise". I incorrectly assumed it was something that we handled automatically but it turns out we don't. So instead, make the process crash on unhandled promise and rely on ECS to start a new task in that case. This should hopefully cover most failure cases.
=> crash on unhandled promise

base/git/git.go, githubbot/README.md, githubbot/db.sql, githubbot/githubbot/db.go, githubbot/githubbot/handler.go, githubbot/githubbot/http.go, githubbot/githubbot/util.go
Add Github release event support
For we can track new release events from the GitHub repo.
- Install the bot
- subscribe to a new release
- wait the release events: `!github subscribe <REPO> releases`
=> add github release event

githubbot/githubbot/db.go
I believe this check should have been updated when the new `releases` event type was introduced on #263
=> fix events length check
